### ISSUE TITLE
boolean is an unsupported format

### ISSUE THREAD

**Issue by mrbar42** [aerospike/aerospike-client-nodejs#104]
At the moment, passing a Boolean as a bin value will result in this error
`Boolean datatype not supported`

As can be seen here [src/main/util/conversions.cc](https://github.com/aerospike/aerospike-client-nodejs/blob/master/src/main/util/conversions.cc#L1022)
Snippet:
```c
else if( as_val_type(val) == AS_BOOLEAN) {
    as_val_destroy(val);
    as_v8_error(log,"Boolean datatype not supported");
    return AS_NODE_PARAM_ERR;
}
``` 

I see no reason why Boolean should not be converted to a number.
it can't be that such a complex types are support such as List and Map and the simplest of them all isn't.
after all a Boolean is probably the closest thing to a number anyways.
```javascript
true == 1 // true
false == Booleans(0) // also true
true === 1 // false - for obvious reasons
```

further more, enforcing non undefined values wrongly forces the programmer to remove undefined values from its record - a non-javascript'ish pattern.
the most logical thing would be to simply ignore the bin.
```c
if( value->IsUndefined()) {
  as_v8_error(log, "Bin value passed for bin %s is undefined", *String::Utf8Value(name))
  return AS_NODE_PARAM_ERR;
}
```

final suggestion for handling input record:
`null` - explicitly empty the bin (e.g delete)
`undefined` - ignore the bin as if it wasn't there
`boolean` - convert to number (MUST be mentioned in the docs - though will not bother most of the programmers)

Leading agenda - the most important thing is to bootstrap the db for most of the cases out of the box.
the advances programmer will find advanced ways to achieve his advances goals.

**Comment by jhecking** [comment]
Thanks for the feedback. Unfortunately boolean is not a [supported data type](http://www.aerospike.com/docs/guide/data-types.html) at the moment. The Node.js client could convert boolean values to an integer value. But when reading back the bin value it would be returned as an integer. Since the information about the actual data type would be lost, the client would not be able to automatically convert the value back to a boolean. Therefore it is recommended that you convert boolean data types to another supported data type within your app, before passing it to the aerospike client. Since your app has knowledge of the semantics of each bin, it can do the appropriate conversion back to boolean data type when reading the value from the DB.

Setting a bin value to `null` already deletes the bin as this small demo shows:

```javascript
var as = require('aerospike')

function check (err) {
  if (err && err.code !== as.status.AEROSPIKE_OK) {
    throw new Error(err.message)
  }
}

var client = as.client({hosts: [{addr: '192.168.33.10', port: 3000}]}).connect(check)
var key = {ns: 'test', set: 'test', key: 'test'}

client.put(key, {i: 1, s: 'foo'}, function (err) {
  check(err)
  client.get(key, function (err, record) {
    check(err)
    console.log(record)
    client.put(key, {i: 1, s: null}, function (err) {
      check(err)
      client.get(key, function (err, record) {
        check(err)
        console.log(record)
      })
    })
  })
})
```

```
$ node test_null
{ i: 1, s: 'foo' }
{ i: 1 }
```

When attempting to set a bin to an `undefined` value the client currently returns a parameter error. I am not convinced that silently ignoring `undefined` bin values would be the right thing to do. It could lead to hard to find application errors if a record gets partially updated because some bin values are undefined. As this would be a backward incompatible changes I would like to hear some stronger arguments than just that it's inconvenient for the programmer to check for undefined values before passing them to the aerospike client.

**Comment by mrbar42** [comment]
I think that we can agree that the user should be aware to the fact that boolean is not supported.
the difference is that i think that it should be learned from the docs while at the moment its returns an error.
same for undefined.

the gain is that the boiler plate is reduced.

But I understand your point of view.
Perhaps these modifications should not be part of the official base driver

**Comment by jhecking** [comment]
Both the general docs on the supported aerospike [data types](http://www.aerospike.com/docs/guide/data-types.html) as well as the specific documentation of the Node.js client's [data model](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/datamodel.md#record) clearly state the supported data types. And Boolean is not among the supported data types at the moment. I can add a note to state that no automatic type conversion is being performed either.

I do not believe there is currently any documentation that states the behaviour when a bin value is set to `null` or `undefined`. I will add that if it doesn't exist yet.

Are you ok to close this issue?

**Comment by mrbar42** [comment]
yes.

thanks for the responses

**Comment by jhecking** [comment]
I've added notes to the [data types](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/datamodel.md#unsupported-data-types) and [`put` command](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/client.md#putkey-record-metadatanull-policynull-callback) documentation.
