### ISSUE TITLE
Discussion: error first callbacks, API changes

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [aerospike/aerospike-client-nodejs#105]
As per discussion on #11 and short email correspondence with Alvin R. of Aerospike, I want to propose some API changes. Those might be friendlier to the `node` developer as it adopts `error-first`callbacks being `null` on success and generally rather resemble other DB interfaces.

**Motivation:**
The DB is awesome, but the client's API is hard to teach and kind of verbose. 

Since porting the tests will take a while I wanted to have the discussion and proposal before the effective PR. However afterwards the API should look like the below, with the library changes below that.

```js
'use strict'
const Aerospike = require('./lib/aerospike')

let config = {
  hosts: [
    { addr: '127.0.0.1', port: 3000 }
  ]
}

Aerospike.connect(config, function (err) {
  if (err) {
    console.log(err);
  }

  var key = Aerospike.key('test','demo','foo');
  console.log(key);

  var bins = { i : 123, s : "str"};
  var metadata = {ttl : 10000, gen: 1};

  Aerospike.put(key, bins, metadata, function(err, key) {
    if (err) {
      console.log('put error:', err);
    }

    Aerospike.get(key, function(err, rec, meta) {
      if (err) {
        console.log('get error:', err);
      }
      console.log(rec, meta);
    });
  });
})
```

It's fairly easy to port this with the current `cpp` layer below.

```js
var as = require('../build/Release/aerospike.node')

function Aerospike () {
  this.key = as.key,
  this.status = as.status,
  this.status_ok = this.status.AEROSPIKE_OK,
  this.policy = as.policy,
  this.language = as.language,
  this.log = as.log,
  this.scanPriority = as.scanPriority,
  this.predicates = as.predicates,
  this.indexType = as.indexType,
  this.scanStatus = as.scanStatus,
  this.Double = as.Double

  this._currentClient = {}
  this.proto = {}
}

Aerospike.prototype._client = function client (config) {
  let client = as.client(config)
  if (client === null) {
    throw new Error('Client object creation failed - null value returned')
  }

  this.proto = Object.getPrototypeOf(client)

  // TODO: implement subclases
  // if (!proto.createQuery) {
  //   proto.createQuery = proto.query
  //   proto.query = query
  // }

  // if (!proto.createIntegerIndex) {
  //   proto.createIntegerIndex = createIntegerIndex
  // }
  //
  // if (!proto.createStringIndex) {
  //   proto.createStringIndex = createStringIndex
  // }
  //
  // if (!proto.createGeo2DSphereIndex) {
  //   proto.createGeo2DSphereIndex = createGeo2DSphereIndex
  // }
  //
  // if (!proto.LargeList) {
  //   proto.LargeList = LargeList
  // }
  //
  // if (!proto.add) {
  //   proto.add = add
  // }
  //
  // if (!proto.append) {
  //   proto.append = append
  // }
  //
  // if (!proto.prepend) {
  //   proto.prepend = prepend
  // }

  return client
}

Aerospike.prototype.connect = function connect (config, cb) {
  const status_ok = this.status_ok
  this._currentClient = this._client(config)

  this._currentClient.connect(function connectCb (er) {
    if (er.code != status_ok) {
      return cb(er)
    }

    return cb(null)
  })
}

Aerospike.prototype.get = function get (key, policy, cb) {
  const status_ok = this.status_ok

  if (typeof policy === 'function') cb = policy

  this._currentClient.get(key, policy, function getCb (er, record, metadata) {

    if (er.code != status_ok) {
      return cb(er)
    }

    return cb(null, record, metadata)
  })
}

Aerospike.prototype.put = function put (key, record, metadata, policy, cb) {
  const status_ok = this.status_ok

  if (typeof policy === 'function') cb = policy

  this._currentClient.put(key, record, metadata, policy, function putCb (er, key) {

    if (er.code != status_ok) {
      return cb(er)
    }

    return cb(null, key)
  })
}

module.exports = new Aerospike()
```

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking I am currently making this work method by method. It's a little hard to send a PR with tests working. So this might take a while or we could work together on this. Most work will anyhow be parameter handling in the `js` layer and porting the tests. Also I haven't subclasses the other classes yet.

**Comment by mrbar42** [comment]
I also want to mention that not all non-OK responses are necessarily errors.
to explain here is a snippet from sugar class I built on top of the current client (this also normalizes the callback pattern).

```javascript
var POSITIVE_STATUS = [
    status.AEROSPIKE_OK,
    status.AEROSPIKE_ERR_RECORD_NOT_FOUND,
    status.AEROSPIKE_ERR_LDT_BIN_DOES_NOT_EXIST
];

function handleResponse(callback) {

    return function (status, result) {
        if (status && POSITIVE_STATUS.indexOf(status.code) == -1) {
            callback(status);
        }

        callback(null, result);
    }
}

client.put(key, value, handleResponse(callback))
```

in my vision "NOT_FOUND" codes are NOT errors and should be derived from the result value.

**Comment by jhecking** [comment]
@eljefedelrodeodeljefe, thanks for getting this started! I like the direction you are taking this, esp. moving some of the parameter handling logic into the JS layer.

I'm a bit concerned about removing the client interface from the JS API completely and putting all the functions on the `Aerospike` interface instead. This makes it impossible to connect to multiple AS clusters. There is also no way to shut down the AS connection cleanly, i.e. no way to call `client.close()`. The native C client is holding resources and there should be a way to release those.

I'll provide more specific feedback on the PR itself. Thanks again for your time and effort!

**Comment by jhecking** [comment]
@mrbar42, I think which responses constitute an error case and which are considered ok is application specific. Regarding your example, I am sure there are lots of use cases where it definitely is considered an error if a record does not exist. That's why the error object has a status code so that the application can handle each error case appropriately.

Are you suggesting we just add the status code into the result value instead? Would that just mean that the application would have to check both the error and the status code in the callback, e.g.

```js
client.get(key, function (err, result) {
  if (err || result.status !== status.OK) throw new Error("something went wrong!")
  // handle "good" results
})
```

That doesn't seem like an improvement over the current callback behavior to me.
})

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking I'll see. I think I can factor this in or at least allow it only as singleton. Both should be technically possible and you could just have developer education pointing at the way you'd prefer. I'll investigate.

Concerning @mrbar42's point: i think we could also have some hybrid handling like the below. But this would be up to you, since it's rather the DBs API.

```js
Aerospike.prototype.get = function get (key, policy, cb) {
  const status_ok = this.status_ok

  if (typeof policy === 'function') cb = policy

  this._currentClient.get(key, policy, function getCb (er, record, metadata, key) {

    switch (er.code) {
      case status_ok:
        return cb(null, record, metadata, key, er) // return er as status
        break;
      case status_not found
        return cb(null, null, null, null, er) // return er as status
        break;
      default:
        return cb(er)
    }    
  })
}
```

Please note, that I'd like to compare against integers (STATUS_OK will likely be always 0, right?) in a future commit to avoid references to `this` or in this case local variables.

**Comment by eljefedelrodeodeljefe** [comment]
In general I'd be +0 on not having `NOT_FOUND` in there. This would massively simplify APIs, I see especially with `redis` where you'd need to check for the `not_found` yourself, but basically treat it the same way.

```js

Aerospike.get(key, function(err, rec, meta) {
   if (err && !rec) {
     res.send(404, "no results here")
   }
  res.json(rec)
});
```

**Comment by jhecking** [comment]
@eljefedelrodeodeljefe, I'm not sure what's the point of returning the error object as a separate status parameter in the callback? It looks a bit weird to me that you would be sending the same error/status object but depending on error/no-error case you would send it in first/last position in the callback.

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking Personally I wouldn't do this either. But I thought if someone likes to use the API in the old way, he could use it by checking what I would call the `status` return parameter. It's redundant though.

**Comment by eljefedelrodeodeljefe** [comment]
Also the tests would currently depend on it, since you somethimes check for non-`AEROSPIKE_OK` statuses.

**Comment by jhecking** [comment]
I have yet to hear anyone speak up strongly for the current way we do error callbacks. :-) The only argument is really backwards compatibility. And introducing a separate status parameter wouldn't help with that.

**Comment by jhecking** [comment]
For status codes other than `AEROSPIKE_OK` the API would always send the error parameter which contains the status code. So the tests wouldn't have to change how they check for that.

**Comment by mrbar42** [comment]
@eljefedelrodeodeljefe i don't think that returning the error object as showed in your example is a "correct" pattern for a lib
@jhecking what i meant is that the call will look like this.
as my example points - not found case is most likely to be handled as an app logic rather than an error.

```javascript
client.get(key, function (err, result) {
    if (err) {
        // an ERROR occurred
        throw new Error("something went wrong!");
    }
    else if (!result) {
        // record wasn't found
        // app logic here - not error handling...
    }
    else {
        // record found
        // more app logic
    }
});
```

but lets say the case is client.put than my logic does not apply since if in any case a "not found" error is returned when inserting to db then its a failure to perform the task hence its an error.

wait so are you suggesting different error handling per method?? kind of a yes.

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking okay. That's even better and I'll refactor to just checking fore error values of `0` and otherwise pass the error to the app as it is in there now. @mrbar42 Okay so my takeaway is, there is no error handling needed in the lib, you just want to have an example, that there could be this case (especially in put).

**Comment by jhecking** [comment]
@mrbar42, a `put` request can return a `RECORD_NOT_FOUND` error, if you specify a write policy of `{exists: UPDATE}` or `{exists: REPLACE}`. (I.e. update/replace a record ONLY if it exists.) But again I would think that it is up to the application to decide whether that constitutes an error case or not. The client really doesn't have enough context to decide that. So it should return an error whenever the operation did not succeed.

**Comment by eljefedelrodeodeljefe** [comment]
I think that makes it clear. Thanks.

**Comment by mrbar42** [comment]
what I am saying actually is that the current error handling of the lib is "throw it blindly to app logic" and i straight forward disagree with that.
there is a result object as well that should be used to convey the result of the operation.
at the moment most of the calls will return the record itself pointlessly.

to make my opinion clearer:
##### these should be presented as an ERROR:
- can't connect to db
- params are invalid
- operation timedout
- record busy
etc

##### these should be presented as a RESULT:
- not found when getting record (null)
- not found when putting with policy (mongo returns this object when updating for example`{ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 }`)
- tried removing a record but it wasn't there (per haps a true/false response)
etc

this logic must be part of the lib - because otherwise app logic will always have to generate these result cases. it causes a overhead of handling these cases over and over again.
I will always want to known if the record was deleted or not - i don't care what status is hiding beneath this action result.
that's the point of the lib - converting db language (status codes) to app logic concepts (exists, did update, successfully removed etc).

the lib does non of that at the moment.
the future result of this is that many alternative client libs will pop out because the official driver doesn't actually ease the real world work flow with the db.

**Comment by jhecking** [comment]
@mrbar42, I think I understand where you are coming from. My point of view is that the client library is in fact blind with regards to the context of the application and therefore cannot make the distinction between errors and negative results that you want it to make.

Let's ignore the error cases for a moment because they are too numerous and focus on the negative results. You have listed three specific cases that you would not consider an error in the context of your application(s):

* `get` command returns `RECORD_NOT_FOUND` status
* `put` command returns `RECORD_NOT_FOUND` status when called with update/replace policy
* `remove` command returns `RECORD_NOT_FOUND` status

We would have to add at least one 4th, similar case I think:

* `put` command returns `RECORD_EXISTS` status when called with create policy

Let me think a bit more about whether there are other similar cases, incl. for commands like `operate`, `scan`, `query`, etc. If the set of these non-error, negative result cases is indeed very small and well defined and likely to be the same for the majority of application use cases, then I might reconsider.

**Comment by mrbar42** [comment]
i also treat this as non-error
AEROSPIKE_ERR_LDT_BIN_DOES_NOT_EXIST

you talk about app logic - but the app is going to need to adapt either way to the lib.
the true question is where is it LOGICALLY the better place to place those negative results.
in most cases an error (by definition - failure to perform task) will result in stopping the current action.
so if there is something that doesn't fall under that category it shouldn't be presented as error.

regardless to what you decide, the user of the lib will be able to reach all cases either way.
the difference is whether he will use the status object or the result object.
does it make sense to call X an error?

if someone wants to treat not found as an error he can do it either way

```javascript
client.get(key, value, function (status, record) {
    if (status !== status.AEROSPIKE_OK) {
        // error - including not found
    }
    else {
        // success
    }
});

client.get(key, value, function (err, record) {
    if (err || !record) {
        // error - including not found
    }
    else {
        // success
    }
});
```

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking making progress. Gonna continue tomorrow.

**Comment by jhecking** [comment]
Thanks, @eljefedelrodeodeljefe! Great progress so far.

**Comment by jhecking** [comment]
Wanted to touch base on this once more before we finalize the new API.

As it stands (on branch [`api-refactor`](/aerospike/aerospike-client-nodejs/tree/api-refactor)) there are two different ways to use the new API: Either all commands are send directly through the `Aerospike` object, or through a `Client` instance:

**Aerospike interface:**
```javascript
const Aerospike = require('aerospike')
const config = {hosts: 'localhost:3000'}
Aerospike.connect(config, function (err) {
  Aerospike.put({ns: 'test', set: 'test', key: 'test'}, {i: 1, s: 'foo'}, function (err) {
    if (err) { throw new Error(err) }
    // ...
  })
})
```

**Client interface:**
```javascript
const Aerospike = require('aerospike')
const config = {hosts: 'localhost:3000'}
Aerospike.connect(config, function (err, client) {
  client.put({ns: 'test', set: 'test', key: 'test'}, {i: 1, s: 'foo'}, function (err) {
    if (err) { throw new Error(err) }
    // ...
  })
})
```

I am considering dropping the Aerospike interface. There is some concern that having two different ways to interact with the client could cause confusion among users. And we do need to retain the option to connect to multiple different Aerospike clusters, which requires having separate client interfaces for each connection.

@eljefedelrodeodeljefe, I know you were advocating the Aerospike interface because it is somewhat simpler than the Client interface. But I do think, since we remove the need to call `Aerospike.client()` first before calling `client.connect()` the new Client interface is not much more verbose than the Aerospike interface. Let me know if you feel strongly about this.

@mrbar42, in the new Client implementation I've also made the callback behavior pluggable, i.e. you would have the option to customize the way the error is being passed to your application if you really want.

All the callbacks from the client to the application layer get passed through a new `CallbackHandler` function. The client will come with two implementations: A `DefaultCallbackHandler` which will follow the Node.js conventions and pass the `err` parameter only if the status code of the command is not `AEROSPIKE_OK`. And a `LegacyCallbackHandler` for backwards compatibility, which maintains the callback conventions of the current client version, i.e. all callbacks will have a non-`null` `err` parameter.

You would be able to provide your own callback handler like this:

```javascript
MyCallbackHandler = function (cb, err) {
  if (err && (err.code !== Aerospike.status.AEROSPIKE_OK && err.code !== Aerospike.status.AEROSPIKE_NOT_FOUND)) {
    cb(err)
  } else {
    var args = Array.prototype.slice.call(arguments, 2)
    args.unshift(null)
    cb.apply(undefined, args)
  }
}
Aerospike.Client.setCallbackHandler(MyCallbackHandler)

Aerospike.connect(function (err, client) {
  // ..
})

**Comment by mrbar42** [comment]
Thanks for the update.

the CallbackHandler is a nice idea.
It might be a good idea to include the invoked method somehowto  allow full customization
```javascript
MyCallbackHandler = function (cb, err, method) {
  switch (method) {
    case 'put':
      // ...
    break;
    default:
      // ...
    break;
  }
}
```

As for the interfaces I also think that multiple interfaces should be avoided.
I also strongly advocate supporting multiple simultaneous cluster clients - meaning using instances.
The best syntax in my vision:
```javascript
const Aerospike = require('aerospike');

const client =  Aerospike.client({}, function (err) {
    // optional ready callback
    if (err) {
        // initial connection failed - should continue retrying in background
    }
    else {
        // ready!
        // client.put(....)
    }
});
```

I think its better to think of the client object as an instance rather than a connection - meaning that 
calling client will create an instance that would connect and will be ready at some point.
the client instance will do its best to maintain a connection to the cluster thus allowing the user to create client only once.
the client object can have a Boolean property that will denotes connection status.
why is a `connect` method necessary?

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking no strong feelings there. The way it stands, it serves the purpose i created the PR for. Just as a matter of style I'd like to propose an additional synchronous version of `.connect()`, mainly in order to keep the indentation level as low as possible. At this point I'd only advocate for that. 

```js
const Aerospike = require('aerospike')
const config = {hosts: 'localhost:3000'}

let cllient = Aerospike.connect(config)

client.put({ns: 'test', set: 'test', key: 'test'}, {i: 1, s: 'foo'}, function (err) {
  if (err) { throw new Error(err) }
  // ...
})
```
The pluggable callback handler is really nice. 

With what I see I'd say: shoot. Well done.

**Comment by jhecking** [comment]
> It might be a good idea to include the invoked method somehowto allow full customization

Do you have a specific use case for that? I don't want to add unnecessary complexity.

> why is a connect method necessary?

To maintain backwards compatibility. Either of these two methods for instantiating a client will work:

    Aerospike.connect(config, function (err, client) { ... })

Or

    var client = Aerospike.client(config)
    client.connect(function (err) { ... })

I plan to update the documentation as well as all the tests and examples to use the former method. But the latter will continue to work as well so that existing applications don't break.

**Comment by mrbar42** [comment]
I'm just thinking that passing only error and callback limits the handler to modify the *default behavior*, adding the specific call will allow more custom manipulation. I don't have a strong specific use case. we can just leave it as you've done it and add it in the future.

About the `connect` method - I am not saying it should be removed.
What I'm saying is that it should called automatically on client initiation and the new docs should not include it as a requirement.
The only use case its relevant is when you want a `connected` notification.
for the sake of the example it could be called `.ready(cb)` but that wouldn't denote error handling, so `connect` is in-fact a better name.

**Comment by eljefedelrodeodeljefe** [comment]
@jhecking :thumbsup:

**Comment by jhecking** [comment]
Closing this. The changes that you started in #106 have been merged back into master. However I am not planning an immediate release of the npm package. I am still working on some unrelated performance improvements and want to roll them up together with the API changes into a major 2.0 release of the client.

**Comment by eljefedelrodeodeljefe** [comment]
Thanks for merging. And the roadmap looks good to me. I am heading for a little proof of concept in a project and wanted to use the client. I'll try to install from `master`, but am looking for the final thing!

**Comment by jhecking** [comment]
That would be great if you could give the new API some usage before I release it as an official version. Let me know if you see any issues or have suggestions for further improvements. My goal is that the next time you talk about Aerospike it'll be "The DB is awesome, and the client's API is a joy to use!" ;-)

Besides the changes that you worked on yourself the other main API change is that the Key, Double and GeoJSON data types are now first class JavaScript classes. I.e. they should be initialized using the constructor functions:

    var key = new Key('test', 'test', 'mykey')
    var value = new Double(3.1415)
    var geo = new GeoJSON({type: 'Point', coordinates: [1.58, 68.27]})

I'm also working on documenting the API using jsdoc. Any (good or bad) experience using jsdoc?

**Comment by eljefedelrodeodeljefe** [comment]
:+1: for the new Classes. 

Yeah, going to push this to reddit when you land it on npm. It really will be "The DB is awesome, and the client's API is a joy to use!". Will likely work on some new stuff in the repo also.
