### ISSUE TITLE
touch() operation TTL clarification

### ISSUE THREAD

**Issue by arch1t3ct** [aerospike/aerospike-client-nodejs#156]
It's either a bug or misdocumented. According to http://www.aerospike.com/docs/client/nodejs/usage/kvs/multiops.html op.touch() should be enough to refresh record TTL. But when I check the code, I see:

```js
/**
   * Update the TTL for a record.
   *
   * @param {number} [ttl] - The new, relative TTL to set for the record, when it is touched.
   * @returns {Object} Operation that can be passed to the {@link Client#operate} command.
   */
  touch: function touch (ttl) {
    var op = new Operation(ops.TOUCH)
    op.ttl = ttl
    return op
  }
```

Not only that. After touching the record without TTL parameter in the op, it becomes 4294967295.

**Comment by GavinDmello** [comment]
@arch1t3ct Yea. It refreshes your record TTL to 5 days which is a default value in the server.
You could reduce that value in the conf file or specify a TTL

**Comment by arch1t3ct** [comment]
Correct me if I'm wrong, but 4294967295 in seconds is not 5 days. I did a test where I insert a record with TTL of 2592000 (30 days) and then immediately do a touch() (no TTL param) on it, after which I got the previously mentioned big number which in fact, according to http://stackoverflow.com/questions/33306547/aerospike-created-ttl-in-my-records is a DO NOT EXPIRE number.

Also, if there is a default behavior, it needs to be documented.

**Comment by GavinDmello** [comment]
Whoops, sorry about the 5 day miscalculation. Touch with no parameters was sets the TTL to the default mentioned in the config. And yeah, you're right,  this should be documented.

**Comment by jhecking** [comment]
I will update the documentation for the `touch` operation at http://www.aerospike.com/docs/client/nodejs/usage/kvs/multiops.html to reflect the changes in v2. I will also update the new API docs at http://www.aerospike.com/apidocs/nodejs/module-aerospike_operations.html#.touch to specify the default behavior when the optional `ttl` parameter is not used. (Reset TTL to the default TTL value for the namespace.)

As kporter had already explained in his answer to the referenced [StackOverflow question](http://stackoverflow.com/questions/33306547/aerospike-created-ttl-in-my-records/33310804#33310804), 4294967295 = 0xFFFFFFFF is just the server's special value to indicate that the record will never expire. On the client side we usually use `-1` to express "never expires", e.g. through the new `Aerospike.ttl.NEVER_EXPIRES` constant just introduced in v2.4.3. (The value was used before, just the constant is new.) I will update the client to return this special value as -1 instead of the server's unsigned value.
