### ISSUE TITLE
Scan - broken?

### ISSUE THREAD

**Issue by arch1t3ct** [aerospike/aerospike-client-nodejs#162]
- Node.js v4.4.3
- Aerospike servers: v3.10.1.1
- Aerospike client: v2.2.0 and v2.4.4

```js
var options = {
            concurrent: true,
            nobins: false
};
var scan = aeroClient.scan('tests', 'foo', options);

var stream = scan.foreach();

stream.on('data', function (record) {
            // Blocking script. Just for debugging purposes. Could be actual calculations. 
            var waitTill = new Date(new Date().getTime() + 5 * 1000);
            while(waitTill > new Date()){}
})
```

When this is executed, server drops the connection and logs are have:

`Jan 10 2017 15:03:58 GMT: WARNING (scan): (scan.c:346) send error - fd 639 sz 1048677 Connection reset by peer`
`Jan 10 2017 15:14:36 GMT: WARNING (scan): (scan.c:346) send error - fd 635 sz 1048705 Connection timed out`

So my question is, is this expected behavior? I recall mentioning back pressure support for Aerospike when records could not be processed fast enough. It might work, but only up until processing doesn't become so heavy that servers cannot get responses from the client. Any solutions to this? Shouldn't scan data event be nonblocking no matter how long it takes?

**Comment by jhecking** [comment]
Node runs on a single threaded event loop [1] and your data handler's busy loop is blocking that event loop so that no other I/O events are getting handled. If you need to execute long running calculations in your event handler you might want to consider using [webworker-threads](https://www.npmjs.org/package/webworker-threads) or [cluster](http://nodejs.org/api/cluster.html).

[1] An over-simplification; see this answer on Stack Overflow for a more detailed explanation: http://stackoverflow.com/questions/22644328/when-is-the-thread-pool-used

**Comment by arch1t3ct** [comment]
I think you missed my point. I'm fully aware on how Node.js works. What I don't understand is why the connection is being reset when the processing takes too long. Take MongoDB for example. I just tried and it has no problems with long blocking record processing. It just waits until it can push the next record.

Is it safe to assume that Aerospike does not care if client can't handle the load? So what if I fork a new thread for processing? Eventually that thread will be overwhelmed and most likely run out of memory. So if thats the case, in my humble opinion this is a fundamental flaw that renders Aerospike unusable. Unless I'm missing something? I would love to hear a solution for a way to process all records (no matter how long it takes) in a single process? A use case: counting distinct values.

**Comment by wchu-citrusleaf** [comment]
AER-5137 is a new enhancement we put in server 3.10.0.3, to make sure slow clients do not block server scan resources, after many users voiced that it would be the best behavior.

We've since had some developers voicing that they prefer a long/indefinite timeout.
https://github.com/aerospike/aerospike-server/issues/165

We'll solicit more opinions, and potentially open up a new configuration.

**Comment by jhecking** [comment]
v2.5 is available on [npmjs.com](https://www.npmjs.com/package/aerospike) now. I am going to close this issue. But please feel free to re-open if upgrading to the latest server and client versions and setting the socket timeout does not resolve the problem.
