### ISSUE TITLE
Possible memory leak during batchRead

### ISSUE THREAD

**Issue by GavinDmello** [aerospike/aerospike-client-nodejs#167]
We're doing a lot of batchReads with the bins selection. The memory keeps creeping up.
Switching it to batchSelect (deprecated method) works pretty well.

Is this is a known issue ?

**Comment by jhecking** [comment]
I believe the memory leak is caused by an issue in the Aerospike C client library: aerospike/aerospike-client-c#62. The Node.js client uses the C client library internally.

A new C client version v4.1.5 has just been released that contains a fix for this issue. I will need to update the Node.js client to use the latest C client version.

**Comment by GavinDmello** [comment]
@jhecking Thanks
