### ISSUE TITLE
Event loop resources have already been released! Call Client#close() with releaseEventLoop set to false to avoid this error

### ISSUE THREAD

**Issue by suthio** [aerospike/aerospike-client-nodejs#169]
AWS Lambda execution environment 
NodeJS4.3

execute this program 
```
      Aerospike.connect({ hosts: '127.0.0.1:3000' }, function (error, client) {
        if (error) {
          throw error
        }
        var key = new Key('foo', 'bar', '10')
        var udf = { module: 'module1', funcname: 'func1', args: ['10', 'array'] }
        client.execute(key, udf, function(error, result) {
          if (error) {
            throw error
          }
        })
        client.close()
      });
```

error
```
Error: Event loop resources have already been released! Call Client#close() with releaseEventLoop set to false to avoid this error.
at new Client (/var/task/node_modules/aerospike/lib/client.js:41:11)
at Aerospike.client (/var/task/node_modules/aerospike/lib/aerospike.js:137:10)
at Aerospike.connect (/var/task/node_modules/aerospike/lib/aerospike.js:153:21)
at /var/task/ad_group_aggregate.js:136:18
at Array.forEach (native)
at applyAerospikeAdGroups (/var/task/ad_group_aggregate.js:134:24)
at handler (/var/task/ad_group_aggregate.js:219:4)
```

Please show the way to solve it

**Comment by jhecking** [comment]
I believe what's happening in this scenario is that an instance of your AWS Lambda handler function gets reused to serve multiple requests. The short answer is that you can try calling `client.close(false)` which should prevent this error from happening.

The more complex answer is that the stateless AWS Lambda programming model is not a very good match for Aerospike's client-server architecture. Establishing a new connection to the Aerospike cluster requires multiple round-trips to each server node to establish the cluster state, etc. That is quite a lot of overhead if you are only executing a single database command within your handler.

You could try to reuse the client connection across multiple handler invocations by keeping a reference to the established client connection outside of your handler function. Something like this:

    var asClient
    
    function connect(callback) {
      Aerospike.connect({ hosts: '127.0.0.1:3000' }, function (error, client) {
        if (error) throw error
        asClient = client
        callback(asClient)
      })
    }

    function executeUdf(client) {
      var key = Key('foo', 'bar', 10)
      var udf = { module: 'module1', funcname: 'func1', args: ['10', 'array'] }
      client.execute(key, udf, function (error, result) {
        if (error) throw error
      })
    }

    exports.handler = function (event, context) {
      if (asClient) {
        executeUdf(asClient)
      } else {
        connect(executeUdf)
      }
    }

[Note that I have not tested this code and it might not work at all.]

But this approach has it's own unique set of challenges: Since you have no control over when and how AWS Lambda reuses a container to execute your handler, you have no control over how many client instances will be created. And since you cannot explicitly close connections to the cluster you might run into issues with two many connections being opened. Whether this model might work depends on your exact use case, e.g. whether your event source is [stream based or not](http://docs.aws.amazon.com/lambda/latest/dg/concurrent-executions.html). You will have to tune parameters such as connection timeouts, max. number of connections, etc. carefully.

See also this interesting comment by Pratik J. from AWS that touches upon some of the same issues: https://github.com/sequelize/sequelize/issues/4938#issuecomment-245211042
