### ISSUE TITLE
Issue with query in the event loop

### ISSUE THREAD

**Issue by blaazetech** [aerospike/aerospike-client-nodejs#199]
We been trying to heavily do the query on a set, but with default configs we got this error.
```
Query:{"client":{"config":{"hosts":[{"addr":"127.0.0.1","port":3000}],"port":3000,"sharedMemory":{"key":2768240640,"takeoverThresholdSeconds":2}},"as_client":{},"connected":true,"captureStackTraces":false},"ns":"foo","set":"buoylimits","filters":[{"predicate":1,"bin":"low","datatype":1,"type":0,"min":790381923,"max":790512993}],"selected":["low","high","data"]}
Error:{"message":"Max node/event loop BB9EA9FC9D98412 async connections would be exceeded: 300","code":-7,"func":"as_event_get_connection","file":"src/main/aerospike/as_event.c","line":426}
```

as of now i have changed the maxConnsPerNode to 3000, but we need to know does it keeps the connections as in open and idle or does it reuse them.
Can you please give a brief about connection setup, reuse and reap terminology used under the hood.

**Comment by blaazetech** [comment]
Even after raising to 3000 connections per node, it started to throw the error again.
```
Error:{"message":"Max node/event loop BB9500D036E3A0E async connections would be exceeded: 3000","code":-7,"func":"as_event_get_connection","file":"src/main/aerospike/as_event.c","line":426}
```

**Comment by jhecking** [comment]
The client uses a per-node connection pool. The [maxConnsPerNode](http://www.aerospike.com/apidocs/nodejs/Config.html#maxConnsPerNode) config sets the max. number of open connections per node (number of currently active connections + number of idle connections remaining in the pool).

**Comment by blaazetech** [comment]
We are running our node.js app with cluster enabled, and it runs on 6 cores, so considering this it with 3000 of maxConnsPerNode, will it be 3000 per client instance or is it aggregated?

i have seen once this value after we raising it to 3000 in the asinfo
```
client_connections=4280
```
if that's the case it should go to 18000 rite?

please share some details about how the connections are reused under this pool.

**Comment by jhecking** [comment]
> If that's the case it should go to 18000 rite?

If you are using the Node.js Cluster module and each worker has it's own client instance, then the max. number of connections per AS server node would be `no_workers * (maxConnsPerNode + 1)` or `(no_workers * maxConnsPerNode) + 1` if you are using shared memory for the partition maps. (The +1 connection is for the tend thread.) So it should indeed be ~18,000 connections in your setup.

> Please share some details about how the connections are reused under this pool.

When the client is executing a new single-key command (e.g. put, get, operate, etc.), it will first try to take an idle connection from the connection pool for the cluster node which is the master for the partition to which the key belongs. If there are no idle, valid (see below) connections, then it will try to create a new connection. If this would exceed the max. limit for connections to a single node (i.e. `maxConnsPerNode`) the client will return an error. Once the command was executed successfully, the client will return the connection back to the pool. In the case of a socket error, while executing the command, the client will release the connection without returning it to the pool.

> Or is it possible to set some timeout to remove idle connections after some time? I saw Java client of Aerospike is offering this, hope same can be made available here.

I assume you are referring to the Java client's [maxSocketIdle](http://www.aerospike.com/apidocs/java/com/aerospike/client/policy/ClientPolicy.html#maxSocketIdle) client policy setting. Note that this setting is ignored for async commands, though: "This field is ignored by asynchronous transactions since these transactions use a non-blocking read to determine if the socket is active and empty." The same applies to the Node.js/C client: When the client takes an idle connection from the per-node connection pool, it performs a non-blocking read and discards the connection if the socket is no longer valid.

**Comment by blaazetech** [comment]
Thanks for the info @jhecking but what about the multi-key commands like query/batchRead, how many connections do they require?, if they reuse the connections how do they operate under the hood?

**Comment by jhecking** [comment]
For multi-key commands it depends on the specific command. `Client#batchRead`, `Scan#foreach` and `Query#foreach` (without UDF) all use a single connection to each server node from the same connection pool that the single-key commands use.

Other commands like the older `Client#batchGet`, `Client#batchSelect`, `Client#batchExists` commands, as well as `Query#apply` for query aggregations, use the C client's synchronous I/O methods under the hood and behave differently.

**Comment by blaazetech** [comment]
Thank you very much for the information, case is closed :)
