### ISSUE TITLE
Client connections is over utilized

### ISSUE THREAD

**Issue by blaazetech** [aerospike/aerospike-client-nodejs#216]
Hi @jhecking, 

we been using Aerospike in many of our setups, the following is the snapshot of the measurements which we observed on same setup of our application with 2 different versions of the aerospike client in node.js

with AS node.js client v 2.7.2(installed from git) and AS server Version 3.13.0.1

```
[root@box1 ~]# ss -s
Total: 13304 (kernel 14463)
TCP:   12593 (estab 12052, closed 499, orphaned 0, synrecv 0, timewait 1/0), ports 0

Transport Total     IP        IPv6
*	  14463     -         -        
RAW	  0         0         0        
UDP	  5         3         2        
TCP	  12094     10724     1370     
INET	  12099     10727     1372     
FRAG	  0         0         0  
```

```
[root@box1 ~]# asinfo -v statistics -l | grep 'client_connections'
client_connections=5107
```

with AS node.js client v 2.5.2(installed from npm) and AS server Version 3.13.0.1

```
[root@box2 ~]# ss -s
Total: 10109 (kernel 13175)
TCP:   9404 (estab 5209, closed 4155, orphaned 0, synrecv 0, timewait 1/0), ports 0

Transport Total     IP        IPv6
*	  13175     -         -        
RAW	  0         0         0        
UDP	  5         3         2        
TCP	  5249      3937      1312     
INET	  5254      3940      1314     
FRAG	  0         0         0  
```

```
[root@box2 ~]# asinfo -v statistics -l | grep 'client_connections'
client_connections=1864
```

**Comment by blaazetech** [comment]
please note our box1 AS node.js client is having all your modifications till August 18, 2017.

**Comment by jhecking** [comment]
That's an interesting observation! I have been trying to reproduce the increase in socket connections using the client benchmark suite but haven't been able to.

1. What kind of client operations do you use in your application? Single-key operations like put/get/..., batch operations (e.g. batchRead) or query/scan operations?
2. What value is `maxConnsPerNode` set to and how many processes does your application use (e.g. if you use Node.js cluster mode)?
3. Do you see an increase in open connections over time or are the observed numbers fairly stable? How long has the application been running at the time these measurements were taken?
4. Have you done any changes to your application with regards to how you use the Aerospike client, e.g. esp. have you started to use Promises instead of callbacks with the client build from the master branch?

If possible, could you rerun your measurements using the latest released client version v2.7.2? It would be good to know whether the issue was introduced in any of the v2.6/v2.7 client releases or is caused by some of the unreleased changes in the master branch.

**Comment by blaazetech** [comment]
Hi @jhecking 

Let me answer all of the questions in order.

1. We do use all kinds of operations, put,get,scan,query,batchread,exists,remove,operator
2. maxConnsPerNode: 200000
3. numbers are fairly stable overtime, and these numbers were captured on a 4 days old process running alive.
4. no changes or alterations made and we are not using Promises.

fyi, we ran with latest code built from git repo clone, and the results of box1 are given above.

**Comment by jhecking** [comment]
@blaazetech, thanks for the detailed answers. I don't have a good idea yet, what could be the cause of this issue. Would it be possible to also run your app with the last released version v2.7.2 of the client and report the results? I would like to narrow down whether the issue was introduced between v2.5.2 and v2.7.2 or whether it only exists on the master branch. I will do further testing on my end in the interim as well.

**Comment by jhecking** [comment]
Hi @blaazetech,

Sorry, two more questions:

1. Have you noticed any other symptoms besides the increased number of client connections, e.g. increased latency, increased memory usage, increased error rates, etc.
2. The master branch contains some breaking changes since the last official v2.7.2 release. E.g. record callbacks now pass a single `Record` object parameter instead of passing three separate `bins`, `meta`, `key` parameters. Also, the semantics of the `exists` operation have changed. Have you updated your app to account for these breaking API changes? (More, but not yet fully complete info at https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md.)

**Comment by jhecking** [comment]
@blaazetech, I have not yet identified any specific change that could explain the increase in open client connections. Since I'm about to release v3.0 of the client, I wanted to quickly check if you've had a chance to review the [additional questions](https://github.com/aerospike/aerospike-client-nodejs/issues/216#issuecomment-331328536) I posted last week?
