### ISSUE TITLE
Unexpected result with getByValueRange

### ISSUE THREAD

**Issue by caoyi0905** [aerospike/aerospike-client-nodejs#234]
This script should output `{ map: [ 'value2' ] }`, but got `{ map: [ 'value2', 'value3' ] }`

``` js
'use strict';

const Aerospike = require('aerospike');
const maps = Aerospike.maps;
const key = new Aerospike.Key('test', 'demo', 'key1');

let items = {
	value1: 1.0,
	value2: 2.0,
	value3: 3.0,
};
let ops = [
	maps.putItems('map', items),
	maps.getByValueRange('map', 2.0, 2.9, maps.returnType.KEY),
];

Aerospike.connect((error, client) => {
	if (error) throw error;
	client.operate(key, ops, (error, record) => {
		if (error) throw error;
		console.log(record.bins);
		client.close();
	});
});
```

**Comment by jhecking** [comment]
Looks like you figured this one out by yourself. :-) But for other users who might stumble upon this: The issue here is how Javascript and Aerospike handle floating point vs. integer numbers. Javascript only has a single numeric type and therefore "2.0" and "2" are treated exactly the same. Therefore the two values ("1.0", "2.0" and "3.0") get stored as integer values in the DB. Aerospike does not do any automatic conversion between integer and floating point numbers. Since the range end parameter in the `getByValueRange` function is a floating point value ("2.9") the comparison with the actual values does not work and the function returns all keys corresponding to the values equal to or greater than the range start value (the integer 2).

When dealing with floating point numbers, it is best to explicitly declaring them as double-precision floating point numbers by using the `Aerospike.Double` class:

`index.js`:

```javascript
const Aerospike = require('aerospike')
const maps = Aerospike.maps
const key = new Aerospike.Key('test', 'demo', 'key1')

let items = {
	value1: new Aerospike.Double(1.0),
	value2: new Aerospike.Double(2.0),
	value3: new Aerospike.Double(3.0)
}
let ops = [
	maps.putItems('map', items),
	maps.getByValueRange('map', new Aerospike.Double(2.0), new Aerospike.Double(2.9), maps.returnType.KEY)
]

Aerospike.connect((error, client) => {
	if (error) throw error
	client.operate(key, ops, (error, record) => {
		if (error) throw error
		console.log(record.bins)
		client.close()
	})
})
```

    > node index.js
    { map: [ 'value2' ] }

**Comment by caoyi0905** [comment]
@jhecking  Thank you very much!
