### ISSUE TITLE
Client timeout

### ISSUE THREAD

**Issue by lokeshlal** [aerospike/aerospike-client-nodejs#248]
Hi,

I am getting following error while running queries.

I am using node.js client and following command.

`client.apply(key, udf, { timeout: 1000 }, function (error, result) 
`
if i increase timeout to a greater value such as 100000, then it works but takes a lot of time.

any suggestions.

Thanks,
Lokesh
```

 AerospikeError: Client timeout: iterations=1 lastNode=172.28.128.3:3000
    at Function.fromASError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\error.js:113:19)
    at OperateCommand.convertError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:88:27)
    at OperateCommand.convertResponse (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:98:22)
    at asCallback (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:160:22)
  name: 'AerospikeError',
  code: 9,
  command:
   OperateCommand {
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        as_client: AerospikeClient {},
        connected: true,
        captureStackTraces: false },
     args: [ [Object], [Array], [Object], [Object] ],
     callback: [Function],
     captureStackTraces: false,
     key:
      Key {
        ns: 'test',
        set: 'set1',
        key: 250,
        digest: <Buffer 33 23 3d ec 53 7b 2f 01 27 bf 73 5a 4f 3b dd a7 42 89 93 a4> } },
  func: 'as_event_total_timeout',
  file: '..\\..\\src\\main\\aerospike\\as_event.c',
  line: 688,
  inDoubt: true }
```

**Comment by jhecking** [comment]
Would it be ok for you to share the UDF function that you are applying, so that we might assess why it might take so long to execute that function? Do you see any errors/warnings in the server log when you apply the function? Maybe you can try to increase the [log level](https://www.aerospike.com/docs/operations/configure/log/index.html) for the UDF subsystem on the server, e.g.

    logging {
      console {
        ...
        context udf debug
      }
    }

**Comment by jhecking** [comment]
Hmm, I just noticed that based on the error you posted, the timeout occurred while executing an OperateCommand, rather than an ApplyCommand. Do you use `Client#operate` and might the timeout have occurred during that command?

If you are unsure where in the execution of your program the error occurred, it might be helpful to temporarily [turn debug stacktraces on](https://www.aerospike.com/apidocs/nodejs/Client.html#captureStackTraces), e.g. by setting the `AEROSPIKE_DEBUG_STACKTRACES` environment variable to true. With that setting enabled, the `AerospikeError` will capture the stacktrace at the moment the command was executed. (At a significant performance overhead, though.)

**Comment by lokeshlal** [comment]
thanks @jhecking. Yes I am using operate command. Same here if I use timeout to be a large value then it takes a lot of time, otherwise it fails with the above error.

I will try to get more insights from the udf log file.

I am using aerospike vagrant build (version 3.15) running in a cluster mode with 3 instances.

```
let movieRecordOps = [
	Aerospike.lists.append("ratings", { "userId": userId, "rating": rating, "ts": ts })
]
client.operate(key, movieRecordOps, meta, { timeout: 1000 },  
	function(err, bins){
		if(err) {
			console.log("err123", err);
			failure(err);
		}
		else {
			// console.log("bins", record);
			success({
				genres: record.genres,
				title: record.title});
		}
	}
);
```

**Comment by jhecking** [comment]
The operate command does not use UDF so the cause for these extreme latencies must be something else. Are other operations like put, get, etc. fast or every request you send to the cluster takes this long? And do you get the timeouts only when processing a large number of requests or even if the server is not under any kind of significant load?

If you are running a 3-node cluster on Vagrant I assume this is just a development setup or some kind of proof-of-concept work you are doing?

**Comment by lokeshlal** [comment]
Yes this is a development env and a proof of concept. Other commands are running quite well. except one UDF

```
local function create_or_update(rec)
    if aerospike:exists(rec) then
        return aerospike:update(rec)
    else
        return aerospike:create(rec)
    end
end

function insert_in_genre(rec, movieId, title, rating, ts)
    local movies = rec["movies"]
    local index = 1
    local found = false
    for movie in list.iterator(movies) do
        if movie.movieId == movieId then
            found = true
            break       
        end
        index = index + 1
    end
    if found == true then
        list.remove(movies, index)
    end

    list.append(movies, map { movieId= movieId, title= title, rating= rating, ts= ts })
    rec["movies"] = movies
    create_or_update(rec)
end
```

**Comment by lokeshlal** [comment]
Getting same for apply as well. I will get the logs and post it here

```
AerospikeError: Client timeout: iterations=1 lastNode=172.28.128.3:3000
    at Function.fromASError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\error.js:113:19)
    at ApplyCommand.convertError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:88:27)
    at ApplyCommand.convertResponse (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:98:22)
    at asCallback (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:160:22)
  name: 'AerospikeError',
  code: 9,
  command:
   ApplyCommand {
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        as_client: AerospikeClient {},
        connected: true,
        captureStackTraces: false },
     args: [ [Object], [Object], [Object] ],
     callback: [Function],
     captureStackTraces: false,
     key: undefined },
  func: 'as_event_total_timeout',
  file: '..\\..\\src\\main\\aerospike\\as_event.c',
  line: 688,
  inDoubt: true }
```

**Comment by jhecking** [comment]
How large is your data set? I can see how the `insert_in_genre` function would be slow if you have a lot of movies per genre, since it potentially needs to iterate through the entire list. Maybe you can store the data as a Map, indexed by movie ID, instead? Then you could use [`maps.put`](https://www.aerospike.com/apidocs/nodejs/module-aerospike_maps.html#.put) to create/update an entry without using a UDF. [Performance](https://www.aerospike.com/docs/guide/cdt-map.html#performance) would still be O(N) by default, but you can reduce that to O(logN) if you order the map by key and create an index.

The `Aerospike.lists.append` operation on the other hand should not degrade in performance even for large lists: As per this [performance chart](https://www.aerospike.com/docs/guide/cdt-list.html#performance), the append operation is O(1).

Please also note that the size of your data structures will be limited by the write block size, which has a max. limit of 1MB. (See [Known Limitations](https://www.aerospike.com/docs/guide/limitations.html).) If you expect to exceed this limit, you will need to structure your data differently, e.g. by creating separate records for each movie rating. If you need help with the data modeling, check out the [Data Modeling topic](https://discuss.aerospike.com/c/how-developers-are-using-aerospike/data-modeling) 
in our user forum.

**Comment by lokeshlal** [comment]
I also noticed a strange behavior. After some inactivity if user try to access a UDF, aerospike throws following error

```
 { AerospikeError: Socket read failed: -4095
    at Function.fromASError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\error.js:113:19)
    at ApplyCommand.convertError (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:88:27)
    at ApplyCommand.convertResponse (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:98:22)
    at asCallback (d:\Projects\Coe\Recommendation-engine\code\node_modules\aerospike\lib\commands\command.js:160:22)
  name: 'AerospikeError',
  code: -6,
  command:
   ApplyCommand {
     client:
      Client {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        as_client: AerospikeClient {},
        connected: true,
        captureStackTraces: false },
     args: [ [Object], [Object], [Object] ],
     callback: [Function],
     captureStackTraces: false,
     key: undefined },
  func: 'as_uv_command_read',
  file: '..\\..\\src\\main\\aerospike\\as_event_uv.c',
  line: 273,
  inDoubt: true }
```

**Comment by jhecking** [comment]
-4095 is libuv's [`EOF` error code](https://github.com/libuv/libuv/blob/v1.x/include/uv-errno.h#L32). Do you see anything in the server logs that might indicate that the server has closed the connection? Any error or warning messages, esp. from the UDF subsystem?

**Comment by jhecking** [comment]
@lokeshlal, any further update on this issue? Where you able to resolve it?

**Comment by lokeshlal** [comment]
@jhecking Yes I was able to resolve. The socket timeout was set to very low value. I increased it and it started working again. However one thing i noticed, sometimes after socket timeout, if an udf query is executed then it breaks. and if a key get command is triggered it worked. thou it is an intermittent issue.

**Comment by jhecking** [comment]
I'll close this issue for now. Let me know if you have any further questions or issues.
