### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by amentain** [aerospike/aerospike-client-nodejs#351]
C-client is now have a FreeBSD support, so please add it in node-client

**Comment by jhecking** [comment]
C client has had FreeBSD support since mid-2018. But we do provide pre-build packages for that platform. I have never tried to compile the Node.js client on that platform. The process would be similar to e.g. Alpine Linux, i.e. you would have to compile the C client for FreeBSD yourself first, then point the Node.js client and the binaries created in that first step, when you build it.

We have a Dockerfile for the Node.js client on Alpine Linux that demonstrates this: https://github.com/aerospike/aerospike-client-nodejs/blob/master/docker/Dockerfile.alpine

Have you given something like this a try already? Any specific issues you encountered?

**Comment by jhecking** [comment]
Duh, ignore my ignorance, please. :-) I realise now the suggestion to "just use Docker" was not very helpful, since running a FreeBSD docker image would require a FreeBSD docker host machine...

Anyway, I tried building the Node.js client on a FreeBSD virtual machine today, but ran into issues building the C client first. I've reached out to our C client dev about this.

In the meantime, can you give us some more background about your specific use case? Are you already using Aerospike on other platforms (e.g. Linux)? Or are you just getting started with Aerospike?
