### ISSUE TITLE
Missing consistency level in write-policy.js

### ISSUE THREAD

**Issue by libterty** [aerospike/aerospike-client-nodejs#383]
In the document we saw there are options that we can set consistency level [data-consistency-level](https://www.aerospike.com/docs/guide/policies.html#data-consistency-level) to `CONSISTENCY_ALL`. However inside the source code we didn't find out there are any options that we can set configuration. Is that nodejs didn't provide this options?

![Screen Shot 2020-08-21 at 11 25 01 AM (2)](https://user-images.githubusercontent.com/38395851/90849176-44b25880-e3a1-11ea-988a-3b9616090f49.png)

**Comment by jhecking** [comment]
That page you linked is unfortunately a bit out-dated. Since the introduction of Strong Consistency (SC) in Aerospike 5, the "consistency level" policy setting has been replaced by two separate "read mode" settings for SC namespaces and AP (availability) namespaces:
* [`ReadPolicy.readModeAP`](https://www.aerospike.com/apidocs/nodejs/ReadPolicy.html#readModeAP__anchor)
* [`ReadPolicy.readModeSC`](https://www.aerospike.com/apidocs/nodejs/ReadPolicy.html#readModeSC__anchor)

The old consistency level settings of `ONE` and `ALL` map to the [`readModeAP` levels](https://www.aerospike.com/apidocs/nodejs/module-aerospike_policy.html#.readModeAP__anchor).

Note: SC mode is only available in Aerospike Enterprise edition.
