### ISSUE TITLE
npm install fails on Windows if user dir has spaces in it

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#441]
One other thing I forgot to mention: If your windows user folder ("c:\Users\Your Name") has spaces on it, the process also fails. It seems that spaces are not properly escaped inside one of the scripts, so you need to run this from an account that has no spaces on its home path -OR- change your current account home path, which might be a little bit nerve wracking.

_Originally posted by @raphaabreu in https://github.com/aerospike/aerospike-client-nodejs/issues/439#issuecomment-986839939_

**Comment by jhecking** [comment]
I wish I had saved the logs when I was having the issues with spaces in the windows user home path, but since that was a huge pain with other apps as well, I decided to do a fresh install and to make sure that I had no spaces in my home folder.

As to where the issue manifested, it surfaced on this line: https://github.com/aerospike/aerospike-client-nodejs/blob/0dc13f7a2dafe0fea27128dad6424f5263f3fa94/scripts/build-c-client.ps1#L99

It seemed to me whatever was calling the 'build-c-client.ps1' was not scaping or using " " to pass arguments, because the arguments seemed to be out of order when the msbuild was being invoked. Moving the project to a folder outside of my home did not help either because one of the paths was pointing to my npm folder insite my user/appdata.

_Originally posted by @raphaabreu in https://github.com/aerospike/aerospike-client-nodejs/issues/439#issuecomment-987892963_

**Comment by DomPeliniAerospike** [comment]
Not planning to fix this, just don't put spaces in the folder name.

**Comment by raphaabreu** [comment]
I understand that this is a minor issue and that there are workarounds, but this sort of answer does say a lot about how a company cares about their developer experience. I have to tell each dev that joins my team that they MUST use a specific folder structure if they are going to touch any repositories that are using Aerospike. Show me one successful technology vendor that does this kind of stuff.

There should be at least a warning so that if someone tries to install in a path that has spaces on it, that they should try installing on C:\whatever instead. I did take the time to go deep into these install instructions to understand what was going on. It is not feasible to have each dev go through this on their own.

Aerospike is an awesome tool, but I make a conscious effort to use it as little as I possibly can because of the developer experience.
