### ISSUE TITLE
Docs: Broken "Client" doumentation

### ISSUE THREAD

**Issue by eagleeye** [aerospike/aerospike-client-nodejs#485]
I can't see methods of Client anymore, it looks broken
https://docs.aerospike.com/apidocs/nodejs/global.html#Client
![image](https://user-images.githubusercontent.com/933445/182161404-944dea1a-c186-48b7-9351-1fe6e534edd8.png)

**Comment by DomPeliniAerospike** [comment]
Hello @eagleeye ,
Sorry for the late response, I am a new developer for this repository, and I am just now getting to the backlog of issues. This was broken for awhile, but I fixed this issue around October when I revamped the API Docs. The client class and other classes listed in typedefs were not being listed due to the class documentation being overridden by the global documentation. https://docs.aerospike.com/apidocs/nodejs/client should contain the information you need. I will close the issue now, but feel free to reopen if you have any additional questions or concerns.
