### ISSUE TITLE
Version 5.1.1 breaks using Docker

### ISSUE THREAD

**Issue by ziyak97** [aerospike/aerospike-client-nodejs#496]
If we use Docker with the latest 5.1.1 version I get the following error - Error: libssl.so.3: cannot open shared object file: No such file or directory

Everything works well with version 5.0.3

This looks like an OpenSSL error and I feel like the Aerospike client is expecting OpenSSL v3 while my container uses v1.

Dockerfile

FROM node:18-bullseye-slim as base

WORKDIR /app

COPY package*.json ./

RUN apt update -y
RUN apt install -y \
    openssl \
    zlib1g

FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon
RUN npm install

COPY . .

CMD ["nodemon", "index.js"]

**Comment by DomPeliniAerospike** [comment]
Hello @ziyak97 ,

Client versions 5.0.3 and before use Openssl@1.1. Client version 5.1.1 uses Openssl@3 due to the machine it was compiled on. If you have a different version of Openssl than the client version does, the build process will not work. To combat this, we changed the build and install process in 5.2.0 to use either Openssl@3 or Openssl@1.1 depending on which version is installed on your machine.  If you upgrade to 5.2.0, this should solve your problem and allow you to use Openssl@1.1.

I highly recommend upgrading to Openssl@3 if your machine is compatible, as Openssl@1.1 has security concerns that are fixed in Openssl@3.  I will close the issue now, but feel free to reopen the issue if you have any more questions or concerns.
