### ISSUE TITLE
Can't launch the library on macOS.

### ISSUE THREAD

**Issue by vlpavlov1** [aerospike/aerospike-client-nodejs#520]
Hello ! 

I have an issue with launching this library on macOS 
Library have been installed as an npm dependency `npm install aerospike`
Nodejs version - 14.18.2
npm version - 6.14.15 

Made some sample code to connect to the DB in docker 
Then trying to lauch this code 
And I'm getting this error everytime : 

`Error: Error loading shared library libssl.so.1.1: No such file or directory (needed by /work/node_modules/aerospike/lib/binding/node-v83-linux-arm64/aerospike.node)`

I can view this file, mentioned in path. And there is a file called `aerospike.node`. That's it. 

Locally I have this version of openSSL (1.1). By running command `which openssl` || `openssl version` I can get correct version (@1.1) 
But I assume this issue is not really about my local OpenSSl / LibSSL version , but something wrong with the library installation or something like this , but I can't find the correct answer to resolve this issue and have a possibility to lauch library / connect to aerospike. Maybe someone can help me with this issue . Thanks in advance !

**Comment by DomPeliniAerospike** [comment]
Hello @vlpavlov1,
I'd be happy to help.  It seems the binding folder is targeting the incorrect OS (Linux instead of Dawin).  For a short term solution, you can delete the node-v83-linux-arm64 folder, go to the lib/binding/openssl@1 folder, find node-v83-darwin-arm64 (or node-v83-darwin-x64) and put that folder in the lib/binding folder.  The targeting with the NPM registry has had some issues, and this will also address in this weeks release.  I will update here when it is released.

One additional note, if you are using Nodejs 14 and an ARM mac, you will have to upgrade to Nodejs 16, as the Client does not support Nodejs 14 with ARM macs.

Let me know if you have any questions.

**Comment by DomPeliniAerospike** [comment]
Hello again @vlpavlov1
Client version 5.2.1 has been release, and should solve the targeting issue you are experiencing. If you are still having difficulties after upgrading, please let us know, and we can work towards a solution
Thanks.

**Comment by mlypniahov** [comment]
@DomPeliniAerospike Please, update docs that compatibility works for v5.2.1   https://developer.aerospike.com/client/nodejs/incompatible#client-does-not-support-nodejs-lts-version-14-on-macos-using-arm-architecture
