### ISSUE TITLE
error TS2304: Cannot find name 'Class'

### ISSUE THREAD

**Issue by raphaabreu** [aerospike/aerospike-client-nodejs#553]
Hello, I am trying to install this package and I am getting the following error on line 853:

![image](https://user-images.githubusercontent.com/3214715/235303457-2fe41eb0-1034-45be-b8fb-af933a1ac375.png)

https://github.com/aerospike/aerospike-client-nodejs/blob/69138fd95981e5fadeb04739b94747486f6d5e91/typings/index.d.ts#L852-L855

Are there any workarounds this?

**Comment by DomPeliniAerospike** [comment]
Hi @raphaabreu,
Sorry for the delayed response.  We have updated our typings in recent version of the aerospike client.  Are you still experiencing this issue on the newest aerospike client version? If you are, we can begin to explore solutions.

**Comment by evrimalacan** [comment]
Hey @DomPeliniAerospike. I updated to the latest version you just released half an hour ago. Typescript build is still failing

<img width="713" alt="Screenshot 2024-01-16 at 20 52 30" src="https://github.com/aerospike/aerospike-client-nodejs/assets/45902796/4c56a71c-7431-4066-b658-12df15af3815">

It's due to these new typings:
https://github.com/aerospike/aerospike-client-nodejs/blob/da309801ddcc3e2017889ab183ff58d4fdff4a3a/typings/index.d.ts#L975C30-L975C30

They must be changed as such:

```typescript
export const expReadFlags: {
      DEFAULT: 0;
      EVAL_NO_FAIL: 16;
}
export const expWriteFlags: {
      DEFAULT: 0;
      CREATE_ONLY: 1;
      UPDATE_ONLY: 2;
      ALLOW_DELETE: 4;
      POLICY_NO_FAIL: 8;
      EVAL_NO_FAIL: 16;
}
```

**Comment by evrimalacan** [comment]
I was eager to update from 5.8.0 to 5.10.0 since you fixed the `npm-run-all` dependency there, but now these typings are breaking our builds, so we'll have to stay at 5.8.0. Let me know if you want me to open a new issue for these.

**Comment by DomPeliniAerospike** [comment]
Hi @evrimalacan,

What commands are you installing the client into your typescript project?

I am not getting the same typescript errors when I compile using tsc, and I want to reproduce the issue you are having.

I'm not an expert with typescript, but I will work to resolve this as quickly as possible.

**Comment by evrimalacan** [comment]
I am running `tsc` as well. My typescript version is `5.3.3`.

Check how the `separators` const is defined here, which doesn't break the build:
https://github.com/aerospike/aerospike-client-nodejs/blob/da309801ddcc3e2017889ab183ff58d4fdff4a3a/typings/index.d.ts#L1189-L1202

The const names is followed by a colon before the brackets, and `CONST` keyword is not repeated 

The `expReadFlags` and `expWriteFlags` are not defined similarly.
That's why I suggested those changes. I also locally tested those changes and `tsc` run successfully. 

Could you also give it a try?

**Comment by DomPeliniAerospike** [comment]
Sorry for the delay @evrimalacan,

I fixed typings/index.d.ts for 5.10 on this branch: https://github.com/aerospike/aerospike-client-nodejs/tree/5.10-TS-FIX.

If you replace _node_modules/aerospike/typings/index.d.ts_ with the file above, you should find the `tsc` will now compile.

Apologies again for the inconvenience, I will confirm that `tsc` works before release of the next Client version releasing in the next few weeks.  Otherwise, this workaround should work for now.

Let me know if you have any problems and I can take another look.  Thanks.

CC @raphaabreu @Nodarii

**Comment by evrimalacan** [comment]
Hey @DomPeliniAerospike,

Do you plan to release a new version with the updated types soon? Our applications are built in CI/CD pipelines, thus we cannot replace files inside `node_modules` at build time. We are waiting for a new version.

**Comment by DomPeliniAerospike** [comment]
Hi @evrimalacan,
We are aiming to release a new version on Wednesday.  Sorry for the delay!

**Comment by evrimalacan** [comment]
Hey @DomPeliniAerospike, it's alright. Thanks a lot for the effort! <3

**Comment by DomPeliniAerospike** [comment]
@evrimalacan 
I forgot to notify, but a new client was released on Friday.  Let us know if you are having any trouble after updating!

**Comment by evrimalacan** [comment]
`5.11.0` works like a charm. Thanks a lot!
