### ISSUE TITLE
Unable to use pnpm package manager because of preinstall script of the package

### ISSUE THREAD

**Issue by baldvic** [aerospike/aerospike-client-nodejs#602]
Hello, 
I'm migrating from yarn package manager to pnpm package manager. Usage of  
```
  "preinstall": "npm install @mapbox/node-pre-gyp",
```
blocks the migration. 
In the same time there is dependency with it.
```
 "dependencies": {
    "@mapbox/node-pre-gyp": "^1.0.11",
   ....
}
```

Error from `pnpm`:
```
node_modules/.pnpm/aerospike@5.10.0/node_modules/aerospike: Running preinstall script, failed in 492ms
.../node_modules/aerospike preinstall$ npm install @mapbox/node-pre-gyp
│ Usage Error: This project is configured to use pnpm
│ $ npm ...
└─ Failed in 492ms at /node_modules/.pnpm/aerospike@5.10.0/node_modules/aerospike
```

Package version details:
```json
{
  "name": "aerospike",
  "version": "5.10.0",
  "description": "Aerospike Client Library",
}
```
Package manager info:
```sh
pnpm
8.15.1
```

**Comment by DomPeliniAerospike** [comment]
Hi @baldvic,

I found an stack overflow that details the issue: [Stack Overflow post](https://stackoverflow.com/questions/72201239/pnpm-install-usage-error-this-project-is-configured-to-use-yarn)

This likely happened because you used corepack to install pnpm/yarn.  [corepack docs](https://nodejs.org/api/corepack.html#configuring-a-package).

When you do this, it adds the "packageManager": property to your package.json, as the stack overflow mentions.

`// package.json
{
 // ...
 "packageManager": "yarn@..."
 // ...
}`

Simply changing this to pnpm@yourversion or pnpm should fix the problem.

If this doesn't work, please reopen this issue and give any details on the failure that is occuring.  I will work to troubleshoot if problems persist.  Sorry for the delay.

**Comment by baldvic** [comment]
Hi, @GayathriKaliyamoorthy ,
Thank you for the advice, but I have properly configured my project with the package manager set to pnpm. I have the following in my projects `package.json`
```json
 "packageManager": "pnpm@8.15.2",
```
And that's an issue.
As my project is configured to use `pnpm` only, it installs all dependencies and executes `preinstall` and `install` scripts using it. So it fails on `aerospike` package on executing `preinstall` script as it uses the `npm` package manager inside it.
https://github.com/aerospike/aerospike-client-nodejs/blob/master/package.json#L41-L42

The actual solution is to do the opposite. I've removed the explicit definition of the package manager in `package.json`, and now `pnpm` manages installing dependencies successfully.

~"packageManager": "pnpm@8.15.2",~
