### ISSUE TITLE
Can't install with node 22

### ISSUE THREAD

**Issue by big-kahuna-burger** [aerospike/aerospike-client-nodejs#619]
Not able to install with node 22. 
Having no issues with node 20.

**Comment by DomPeliniAerospike** [comment]
Hello @big-kahuna-burger,
This issue should be solved with the newest release of the Client: 5.12.1.
In NPM, we added pre-built binaries for Nodejs 22. Release notes: [link](https://download.aerospike.com/download/client/nodejs/notes.html#5.12.1)
Sorry for the delay.
I will close this issue since it should be solved, feel free to reopen if an issue persists.

**Comment by big-kahuna-burger** [comment]
Amazing, thanks for the response.
