### ISSUE TITLE
Docs showing unsupported feature (query UDF)

### ISSUE THREAD

**Issue by courtneycouch** [aerospike/aerospike-client-nodejs#65]
The docs show that a query UDF is supported: http://www.aerospike.com/docs/client/nodejs/usage/query/query_udf.html

Seems that this is actually *not* the case:
https://github.com/aerospike/aerospike-client-nodejs/blob/769b2051e2359ab4f37f00eef23af61227589150/lib/aerospike.js#L58-L59

Any ETA on actually implementing this? Also it would be really helpful if unsupported features actually throw errors instead of, I don't know, silently doing nothing...

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We will fix the documentation and make it consistent with code. Thanks for reporting this.

**Comment by courtneycouch** [comment]
Do you have any ETA on this being implemented in the client? I mean fixing the docs is good, but even better would be to fix the client to match the docs ;)

**Comment by wchu-citrusleaf** [comment]
This is now in progress, first for the underlying C client.

**Comment by courtneycouch** [comment]
Any update on this?

**Comment by wchu-citrusleaf** [comment]
We are first concentrating on the db part of the feature. Once that is more solid, will quickly follow with client API. Sorry for the delay.

**Comment by courtneycouch** [comment]
Are you saying that Arerospike doesn't actually support this feature yet? (since you said the db needs work for this)

We were considering adding some of the UDF query bits in Java because it's documented here: http://www.aerospike.com/docs/client/java/usage/query/query_udf.html 

Is this another case of the Aerospike docs claiming functionality that hasn't been built??

**Comment by jhecking** [comment]
The Aerospike Node.js client has had support for applying UDFs on scan/query results since v1.0.26, released Jan 2015, for two different use cases:
* Using a Stream UDF for query aggregation with or without filter predicates,
* Applying a Record UDF to all records in a given namespace/set via background scan (w/o filter predicates).

What was missing was the option to apply a Record UDF while also applying a filter predicate to limit the set of records to which the UDF gets applied. (However it was possible to do the filtering inside the Lua function itself.) The documentation at http://www.aerospike.com/docs/client/nodejs/usage/query/query_udf.html did not state this correctly.

v2.0 of the Aerospike Node.js client supports applying a Record UDF both on scans (w/o filter predicate) and on queries (with filter predicate). In both cases the scan/query will be processed on the server in the background, i.e. the processed records will not be returned to the client.

`aerospike@2.0.0-alpha.3` is available on [npmjs.com](https://www.npmjs.com/package/aerospike) now. The query/scan API in particular has undergone some major changes since v1.0, so please refer to the list of [backward incompatible changes](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md) or the new [API documentation](http://www.aerospike.com/apidocs/nodejs/). For more information about the other changes in the upcoming v2.0 release, please refer to our [recent blog post](http://www.aerospike.com/blog/early-adopter-release-for-aerospike-node-js-client-v2-0/). For follow-up questions, please feel free to use our [community forum](https://discuss.aerospike.com/c/client-libraries/node-js-client) or please file a new ticket here on Github if you encounter any issues with the alpha release.
