### ISSUE TITLE
Contains filter

### ISSUE THREAD

**Issue by IncSW** [aerospike/aerospike-client-nodejs#74]
Can you add contains filter?
https://github.com/aerospike/aerospike-client-c/blob/master/src/include/aerospike/as_query.h#L92

**Comment by jhecking** [comment]
The contains filter predicate is used to filter on list/map membership. This requires support for secondary indexes on lists and maps, which is supported by the Aerospike server starting with the just released version 3.8. Please refer to the [release announcement](http://www.aerospike.com/blog/aerospike-3-8-release/) for further information.

Client side, this feature will be supported in the upcoming Aerospike Node.js client v2.0:

    const Aerospike = require('aerospike')
    Aerospike.connect((error, client) => {
      if (error) throw error
      var query = client.query('test', 'demo')
      query.select('tags')
      query.where(Aerospike.filter.contains('tags', 'blue', Aerospike.indexType.LIST))
      var stream = query.foreach()
      stream.on('error', (error) => { throw error })
      stream.on('end', () => { client.close() })
      stream.on('data', (bins, meta) => {
        // process query results
      })
    })

`aerospike@2.0.0-alpha.3` is available on [npmjs.com](https://www.npmjs.com/package/aerospike) now. The query API has undergone some major changes since v1.0, so please refer to the list of [backward incompatible changes](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/api-changes.md) or the new [API documentation](http://www.aerospike.com/apidocs/nodejs/). For more information about the other changes in the upcoming v2.0 release, please refer to our [recent blog post](http://www.aerospike.com/blog/early-adopter-release-for-aerospike-node-js-client-v2-0/). For follow-up questions, please feel free to use our [community forum](https://discuss.aerospike.com/c/client-libraries/node-js-client) or please file a new ticket here on Github if you encounter any issues with the alpha release.
