### ISSUE TITLE
Range filter API documentation error

### ISSUE THREAD

**Issue by plelevier** [aerospike/aerospike-client-nodejs#89]
In the following API documentation section : 
- https://github.com/aerospike/aerospike-client-nodejs/blob/master/docs/filters.md#rangebin-min-max

It is said that the min and max parameters are non-inclusive : 
> - min – The minimum value of the bin, the records with bin value greater than min will be returned as part of query result.
> - max - The maximum value of the bin, the records with bin value less than max will be returned as part of query result

But the aerospike's filter.range method documentation tells us those parameters are inclusive : 
https://www.aerospike.com/docs/guide/query.html
> When specifying "RANGE" limits, the result set is inclusive of both limits

Also, since the range filters have to work on numeric values (64 bits), what number should we use in javascript as the `max` numeric value if we want to retrieve everything, starting from a `min` value?

I'm not sure that Number.MAX_VALUE is the best candidate, is it safe to use this through the node.js client?
I'm considering Number.MAX_SAFE_INTEGER (2^53 - 1) as a better alternative, but since the max 64 bits value should be 2^63 - 1, it may drop some records : Is there a better way?

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

Number.MAX_VALUE, will be interpreted as Double in Aerospike server. Range queries are not supported on double datatype. 

Are you writing the records using node.js application and using the same to query ? Or do you write using a language which supports 64 bit integers and reading using node.js?  If you are doing the former, then setting Number.MAX_SAFE_INTEGER should return all the records, because application wouldn't have written values above MAX_SAFE_INTEGER. If you are trying to do the latter, you can specify the value 2^63-1, aerospike can interpret the value as 2^63-1. But when the data is retrieved in a node.js application, the precision will be lost in the application. This is due to the inherent limitation in node.js Number datatype. Be prepared to handle the precision loss.

Thanks.

**Comment by plelevier** [comment]
Hi,

My goal was to understand the limitations of the node client, to study how to fit some of my use cases, given values may be written using the Java client. 

If I understand correctly, it means that the best strategy would be to always check to never put values that are greater than MAX_SAFE_INTEGER when using aerospike clients that are able to handle 64 bits integers, when we're needing to get those values from the node client?

Anyway, thanks for the clarification

**Comment by GayathriKaliyamoorthy** [comment]
Yes, if you are retrieving those integers from Aerospike and processing them in node.js. I would like to clarify that, it's not aerospike node client driver limitation but the limitation from the node.js language. 

Thanks

**Comment by plelevier** [comment]
Ok, thank you for the clarification, that's what I suspected.
