### ISSUE TITLE
No stream control exists

### ISSUE THREAD

**Issue by arch1t3ct** [aerospike/aerospike-client-nodejs#98]
Current implementation does not support any kind of stream control. No pause()/resume(), no end(). How is this still missing? How can one scan all the records and process them partially? 

Try imagining exporting billions of records where you have to simultaneously write it to disk. Not only this won't work in real time (because disks are slow and overflow will happen) nor after processing all scan (billions of records, how much RAM will you need for that?)

**Comment by jhecking** [comment]
@arch1t3ct, if you haven't already, I would suggest you take a look at the recently released v2 client. The query and scan implementation is much improved over the v1 client. While there is still no support for pause()/resume(), the new implementation finally uses non-blocking I/O and no longer buffers the query/scan results on the client side. You'll find that memory consumption is _much_ reduced with the new client.

You can find some more details about the performance improvements we measured in this [blog post](http://www.aerospike.com/blog/win-win-greater-speed-and-lower-latency-with-aerospikes-node-js-client-v2-0/).

**Comment by revington** [comment]
@jhecking I'm missing something or https://github.com/aerospike/aerospike-client-nodejs/blob/master/lib/record_stream.js#L64-L71 is missing a call to its parent?

Like `Readable.call(this, options);`
Also, is there any plan to support `#pause()` I use scan to populate and index in a different database which of course does not have aerospike's performance. Pause is the mechanism that will allow me to control the situation. 

The same applies to other scenarios. Is this a limitation of aerospike or just the client?

**Comment by jhecking** [comment]
@revington, the Aerospike server currently does not support pausing query/scan operations. Therefore implementing pause/resume functionality on the client would necessarily involving buffering the data which I don't think is feasible. The client and server do however throttle the throughput if the client application is not able to keep up. This happens when Node.js is not able to read the incoming data from the socket fast enough, which signals to the server to slow down. In my testing, this works well, e.g. when writing the scan results out to the filesystem (which is slower than reading the in-memory data via AS). The `test/stress/query.js` file contains some related test cases.

The fact that the `RecordStream` class does not call the `Readble` constructor doesn't really make much of a difference. It's probably best to think of `RecordStream` as a pre-node-0.10 legacy stream, that is always in flowing mode and doesn't support pause/resume. (`Stream#pause()` was advisory in Node.js v0.10, rather than guaranteed.)

I've had some success using `Readable#wrap` to wrap a `RecordStream` instance and support pause/resume that way. But that just ends up buffering the data again on the client side. If you have a lot of data to process and you can't process the data as fast as AS send it, you will run out of memory sooner or later.

**Comment by revington** [comment]
@jhecking 

> The client and server do however throttle the throughput if the client application is not able to keep up. This happens when Node.js is not able to read the incoming data from the socket fast enough, which signals to the server to slow down. 
Will be nice to have access to that mechanism via the node.js client api. Specially when you want to dump data to a different system (i.e. an sql DB). and you want to control the job.

**Comment by jhecking** [comment]
@revington,

> Will be nice to have access to that mechanism via the node.js client api. Specially when you want to dump data to a different system (i.e. an sql DB). and you want to control the job.

I understand your problem, but there isn't really any specific mechanism to expose here. It's just the standard TCP/IP flow control measures that control this: If Node.js is not processing the I/O events from the socket connection to the server fast enough, then the network buffer will eventually fill up and the networking stack will signal to the sender (i.e. AS) to slow down.

**Comment by shabber-bambu** [comment]
I am also getting the problem of 

TypeError: stream.pause is not a function

while uploading a stream to blob

**Comment by jhecking** [comment]
Since Aerospike server version 4.7 and client version 3.14, the client/server now support a records-per-second option for scans which throttles the number of records sent by each server node. [1] On the client side, this is enable by setting the [ScanPolicy#recordsPerSecond](https://www.aerospike.com/apidocs/nodejs/ScanPolicy.html#recordsPerSecond) property.

This should be useful if the client application is not able to process the data as fast as the server is sending it, e.g. because it involves writing the data to a different, slower backend system. It is understood, that this is _not_ a full replacement for stream control via pause()/resume(), as the RPS limit needs to be statically _before_ the scan is started and cannot be adjusted dynamically during the scan. But this new scan policy should still address the issue of missing stream control for many (if not all) use cases.

[1] Note that the limit is _per server node_. That means if you cluster consists of 5 server nodes, and you set the recordsPerSecond scan policy to 1,000 RPS, the client will have to be able to handle up to 5,000 RPS.
